### PR TITLE
How to switch or restore wallet with non-pristine Electrum GUI

### PR DESCRIPTION
**Pull request by miohtama**
Added instructions for OSX, but I guess they work for Linux too.

Also the editor automatically sanitized whitespaces from HTML code.

### CODE REVIEW

**Comment by rdymac** [comment]
There are some typos. You may also want to proof-read the added sections as they are not clear enough

**Comment by rdymac** [comment]
This last part is not needed " ./Electrum -w ~/.electrum/electrum.dat ", if the client is run without the -w tag the client will look for the default electrum.dat in the electrum directory

**Comment by miohtama** [comment]
Thanks!

Revisited and updated the text based on the feedback.

**Comment by rdymac** [comment]
It is still a bit confusing for me, but let's see what others say

**Pull request merged**
